"use client";

import { useMemo, useState } from "react";

type Tone = "pass" | "hold" | "review" | "block" | "archived" | "proposed";
type EventRow = {
  key: string; title: string; zone: string; source: string; sources: number; proof: string;
  importance: string; decision: string; reason: string; slot: string; language: string; tone: Tone;
};

const events: EventRow[] = [
  { key: "evt:av:2026-001", title: "Certification EASA d’un nouvel appareil régional", zone: "Europe", source: "EASA · démo", sources: 6, proof: "VERIFIED", importance: "Élevée", decision: "APPROVED_PUBLIC", reason: "Source officielle et impact industriel", slot: "Lead Event", language: "FR", tone: "pass" },
  { key: "evt:av:2026-002", title: "Fermeture temporaire d’un espace aérien stratégique", zone: "Moyen-Orient", source: "NOTAM · démo", sources: 9, proof: "VERIFIED", importance: "Critique", decision: "APPROVED_PUBLIC", reason: "Impact immédiat sur les routes", slot: "Breaking", language: "FR / EN", tone: "pass" },
  { key: "evt:av:2026-003", title: "Incident technique déclaré sur un vol long-courrier", zone: "Asie-Pacifique", source: "Autorité · démo", sources: 2, proof: "DEVELOPING", importance: "Moyenne", decision: "HOLD_PROOF", reason: "Diversité de sources insuffisante", slot: "Continuous Feed", language: "FR", tone: "hold" },
  { key: "evt:av:2026-004", title: "Commande majeure d’avions par une compagnie", zone: "Amérique du Nord", source: "Constructeur · démo", sources: 5, proof: "VERIFIED", importance: "Élevée", decision: "REVIEW_REQUIRED", reason: "Chiffrage à recouper", slot: "Major Grid", language: "FR / EN", tone: "review" },
  { key: "evt:av:2026-005", title: "Nouvelles restrictions de créneaux aéroportuaires", zone: "Europe", source: "Aéroport · démo", sources: 4, proof: "VERIFIED", importance: "Moyenne", decision: "APPROVED_PUBLIC", reason: "Contexte et calendrier établis", slot: "Vertical Lane", language: "FR", tone: "pass" },
  { key: "evt:av:2026-006", title: "Rumeur de rapprochement entre deux compagnies", zone: "Europe", source: "Blog sectoriel · démo", sources: 1, proof: "UNCONFIRMED", importance: "Faible", decision: "BLOCKED", reason: "Rumeur sans confirmation", slot: "—", language: "FR", tone: "block" },
  { key: "evt:av:2026-007", title: "Mise à jour d’une directive de sécurité cabine", zone: "Monde", source: "OACI · démo", sources: 7, proof: "VERIFIED", importance: "Élevée", decision: "APPROVED_PUBLIC", reason: "Référence officielle mondiale", slot: "Dossier", language: "FR / EN", tone: "pass" },
  { key: "evt:av:2026-008", title: "Perturbation durable liée à une météo extrême", zone: "Amériques", source: "Météo / ATC · démo", sources: 8, proof: "DEVELOPING", importance: "Élevée", decision: "HOLD_CONTEXT", reason: "Chronologie encore mouvante", slot: "Timeline", language: "FR", tone: "hold" },
  { key: "evt:av:2026-009", title: "Vidéo d’essai d’un prototype militaire", zone: "Europe", source: "Vidéo · démo", sources: 2, proof: "PARTIAL", importance: "Moyenne", decision: "HOLD_SCOPE", reason: "Impact aviation civile à établir", slot: "—", language: "FR", tone: "hold" },
  { key: "evt:av:2026-010", title: "Rapport final d’un incident de piste", zone: "Afrique", source: "BEA local · démo", sources: 5, proof: "VERIFIED", importance: "Élevée", decision: "APPROVED_PUBLIC", reason: "Rapport factuel disponible", slot: "Dossier", language: "FR", tone: "pass" },
  { key: "evt:av:2026-011", title: "Nouvelle liaison saisonnière annoncée", zone: "Europe", source: "Compagnie · démo", sources: 2, proof: "VERIFIED", importance: "Faible", decision: "ARCHIVED", reason: "Promotion commerciale faible", slot: "—", language: "FR", tone: "archived" },
  { key: "evt:av:2026-012", title: "Déploiement d’une nouvelle procédure ATC", zone: "Asie-Pacifique", source: "Autorité · démo", sources: 6, proof: "VERIFIED", importance: "Moyenne", decision: "PROPOSED", reason: "Valeur explicative à qualifier", slot: "Continuous Feed", language: "FR", tone: "proposed" }
];

const readers = [
  ["01", "Lecteur de périmètre", "Est-ce bien pour ce site ?", "Verticale aviation, entités, thèmes, zones, exclusions.", "Une certification EASA est dans le périmètre ; une politique générale sans effet aérien ne l’est pas.", "PASS", "pass"],
  ["02", "Lecteur de preuve", "Les sources sont-elles assez solides, diverses et cohérentes ?", "Nombre de sources, diversité des domaines, source officielle, contradiction, incertitude, proof_status.", "Une source faible unique pour un incident → HOLD_PROOF.", "HOLD", "hold"],
  ["03", "Lecteur d’importance", "Quel est l’impact réel ?", "Ampleur, sécurité, personnes touchées, portée géographique, importance industrielle, nouveauté.", "Crash, fermeture d’espace aérien ou commande majeure d’avions.", "REVIEW", "review"],
  ["04", "Lecteur de contexte", "Peut-on l’expliquer proprement maintenant ?", "Faits établis, entités identifiées, historique, chronologie, éléments manquants.", "Un événement réel mais encore confus → HOLD_CONTEXT.", "HOLD", "hold"],
  ["05", "Éditeur de sortie", "Quel format sert le mieux l’utilisateur ?", "Urgence, profondeur, langue, image, vidéo, historique.", "Breaking, Lead Event, Major Grid, Vertical Lane, Continuous Feed, Dossier, Timeline, Video Wall.", "PASS", "pass"],
  ["06", "Gate", "Bloque ou autorise WeyOutput ?", "Contrat futur : PROPOSED, HOLD_SCOPE, HOLD_PROOF, HOLD_CONTEXT, REVIEW_REQUIRED, APPROVED_PUBLIC, BLOCKED, ARCHIVED.", "Aucune transition n’est exécutée dans cette V1.", "REVIEW", "review"]
] as const;

const newsReaders = [
  ["01", "Lecteur de périmètre", "Cet événement appartient-il réellement à NewsWey ?", "Nature du fait, thèmes, entités, zones touchées, portée et event_key déjà adapté.", "PASS_SCOPE · HOLD_SCOPE · BLOCK_SCOPE", "Le pays est une vue ; l’event_key reste l’unité centrale."],
  ["02", "Lecteur de preuve", "Que savons-nous réellement et avec quel niveau de certitude ?", "Sources, diversité, source officielle, contradictions, incertitudes, proof_status et liens visibles.", "PASS_PROOF · HOLD_PROOF · BLOCK_PROOF", "L’importance ne remplace jamais la preuve."],
  ["03", "Lecteur d’importance", "Pourquoi cet événement compte-t-il maintenant ?", "Conséquences humaines, sécurité, portée, rupture, nouveauté, secteurs touchés et continuité.", "CRITICAL · HIGH · MEDIUM · LOW", "NewsWey hiérarchise impact, preuve et importance — pas la récence seule."],
  ["04", "Lecteur de contexte", "Peut-on expliquer proprement cet événement maintenant ?", "NOW, WHY NOW, WHY IT MATTERS, LAST TIME, TREND et sources vérifiables.", "PASS_CONTEXT · HOLD_CONTEXT · REVIEW_CONTEXT", "LAST TIME et TREND ne sont jamais inventés."],
  ["05", "Éditeur de sortie", "Quelle présentation sert le mieux le lecteur ?", "Format, profondeur, langue, média qualifié, vue globale/pays/verticale et durée de visibilité.", "RECOMMANDATION UNIQUEMENT", "Un event_key reçoit un emplacement principal ; la traduction vient après la valeur éditoriale."],
  ["06", "Gate", "Le contrat newswey-v1 autorise-t-il cet événement à poursuivre son parcours ?", "Résultats des lecteurs, preuves utilisées, policy_version, raisons et statut d’exécution.", "PROPOSED → APPROVED_PUBLIC", "APPROVED_PUBLIC est verrouillé en observation ; aucun LLM ne l’accorde seul."]
] as const;

const products = [
  { key: "aviationwey", name: "AviationWey", domain: "aviationwey.com", configured: true },
  { key: "bizzwey", name: "BizzWey", domain: "bizzwey.com", configured: false },
  { key: "newswey", name: "NewsWey", domain: "newswey.com", configured: true },
  { key: "artwey", name: "ArtWey", domain: "artwey.com", configured: false },
  { key: "diaswey", name: "DiasWey", domain: "diaswey.com", configured: false },
  { key: "expatwey", name: "ExpatWey", domain: "expatwey.com", configured: false },
  { key: "financewey", name: "FinanceWey", domain: "financewey.com", configured: false },
  { key: "investwey", name: "InvestWey", domain: "investwey.com", configured: false },
  { key: "lifewey", name: "LifeWey", domain: "lifewey.com", configured: false },
  { key: "peoplewey", name: "PeopleWey", domain: "peoplewey.com", configured: false },
  { key: "stadwey", name: "StadWey", domain: "stadwey.com", configured: false },
  { key: "tripwey", name: "TripWey", domain: "tripwey.com", configured: false },
  { key: "971carlease", name: "971 Car Lease", domain: "971carlease.com", configured: false },
  { key: "971container", name: "971 Container", domain: "971container.com", configured: false },
  { key: "971driver", name: "971 Driver", domain: "971driver.com", configured: false },
  { key: "971expats", name: "971 Expats", domain: "971expats.com", configured: false },
  { key: "971familyoffice", name: "971 Family Office", domain: "971familyoffice.com", configured: false },
  { key: "971financial", name: "971 Financial", domain: "971financial.com", configured: false },
  { key: "971info", name: "971 Info", domain: "971info.com", configured: false },
  { key: "971information", name: "971 Information", domain: "971information.com", configured: false },
  { key: "971investment", name: "971 Investment", domain: "971investment.com", configured: false },
  { key: "971jobs", name: "971 Jobs", domain: "971jobs.com", configured: false },
  { key: "971wealth", name: "971 Wealth", domain: "971wealth.com", configured: false },
  { key: "bykema", name: "ByKema", domain: "bykema.com", configured: false },
  { key: "mydubaihome", name: "My Dubai Home", domain: "mydubaihome.com", configured: false }
] as const;

function Tag({ tone, children }: { tone: Tone; children: React.ReactNode }) { return <span className={`tag ${tone}`}>{children}</span>; }

export default function Home() {
  const [selected, setSelected] = useState<EventRow>(events[0]);
  const [panelOpen, setPanelOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [productKey, setProductKey] = useState("aviationwey");
  const activeProduct = products.find(product => product.key === productKey) ?? products[0];
  const aviationActive = activeProduct.key === "aviationwey";
  const newsActive = activeProduct.key === "newswey";
  const filtered = useMemo(() => events.filter(e => `${e.key} ${e.title} ${e.decision}`.toLowerCase().includes(search.toLowerCase())), [search]);
  const openEvent = (event: EventRow) => { setSelected(event); setPanelOpen(true); };

  return <main className="shell">
    <aside className="sidebar">
      <div className="brand"><span className="brandmark">W</span><span>WEY<span>REDACTION</span></span></div>
      <div className="workspace-label">ESPACE OPÉRATEUR</div>
      <nav>
        <a className="nav active"><i>◈</i> Comité de rédaction</a>
        <a className="nav"><i>◎</i> Produits <b>{products.length}</b></a>
        <a className="nav"><i>⌁</i> Policies</a>
        <a className="nav"><i>◌</i> Traçabilité</a>
      </nav>
      <div className="sidebar-bottom"><div className="demo-dot"/> Données de démonstration<br/><small>v1.0 · lecture seule</small></div>
    </aside>
    <section className="content">
      <header className="topbar"><div><div className="crumb">WEYMEDIA / SALLE ÉDITORIALE</div><h1>WeyRedaction <em>·</em> Comité de rédaction</h1><p>Sélection, preuve et visibilité par produit éditorial</p></div><div className="top-actions"><span className="readonly">◉ Lecture seule</span><button className="avatar" aria-label="Opérateur">WR</button></div></header>
      <div className="observation"> <strong>MODE OBSERVATION</strong><span>— aucun événement n’est publié ou modifié depuis cette interface.</span></div>
      <div className="product-row"><div><label>PRODUIT ÉDITORIAL · {products.length} SITES ENREGISTRÉS</label><select className="product-selector" value={productKey} onChange={event => setProductKey(event.target.value)}>{products.map(product => <option key={product.key} value={product.key}>{product.name} · {product.domain}{product.configured ? " — policy V1" : " — policy à définir"}</option>)}</select><p className="registry-note">{activeProduct.domain} · {aviationActive ? "données de démonstration AviationWey" : newsActive ? "policy active en observation · aucun événement réel connecté" : "registre produit créé — aucune policy ni donnée simulée pour ce site"}</p></div><div className="policy-chip"><span>POLICY VERSION</span><b>{aviationActive ? "aviationwey-v1" : newsActive ? "newswey-v1" : "à définir"}</b></div></div>

      {aviationActive ? <>
      <section className="policy card"><div className="section-title"><div><span className="eyebrow">POLITIQUE VERSIONNÉE · NON EXÉCUTABLE</span><h2>Politique AviationWey V1</h2></div><Tag tone="proposed">DÉMONSTRATION</Tag></div><div className="policy-grid"><div><b>product_key</b><code>aviationwey</code></div><div><b>policy_version</b><code>aviationwey-v1</code></div><div className="wide"><b>Objectif</b><p>Observer et expliquer les événements importants de l’aviation mondiale.</p></div><div><b>Périmètre</b><p>Aviation civile, compagnies, avionneurs, appareils, aéroports, autorités, sécurité, incidents majeurs, régulation, espace aérien et défense aérienne lorsque son impact aviation est réel.</p></div><div><b>Exclusions</b><p>Rumeurs, promotions commerciales faibles, contenus hors aviation, doublons, incidents mineurs non confirmés.</p></div><div><b>Exigence</b><p>Faits uniquement, sources visibles, incertitude affichée, aucune opinion.</p></div><div><b>Règle de publication</b><p>Un événement n’est jamais publié directement depuis un signal.</p></div></div></section>

      <section><div className="section-heading"><div><span className="eyebrow">LECTURE MULTI-CRITÈRES</span><h2>Les six lecteurs du comité</h2></div><span className="legend"><i className="pass"/> PASS <i className="hold"/> HOLD <i className="review"/> REVIEW</span></div><div className="reader-grid">{readers.map(([num, name, question, observes, example, status, tone]) => <article className="reader card" key={num}><div className="reader-top"><span className="number">{num}</span><Tag tone={tone as Tone}>{status}</Tag></div><h3>{name}</h3><strong>{question}</strong><dl><dt>Observe</dt><dd>{observes}</dd><dt>Exemple AviationWey</dt><dd>{example}</dd></dl></article>)}</div></section>

      <section className="queue-section"><div className="section-heading"><div><span className="eyebrow">12 CANDIDATS · DONNÉES DE DÉMONSTRATION</span><h2>File éditoriale AviationWey</h2></div><input aria-label="Rechercher" value={search} onChange={e => setSearch(e.target.value)} placeholder="Rechercher un event_key…" /></div><div className="table-card card"><div className="table-wrap"><table><thead><tr><th>EVENT_KEY</th><th>TITRE</th><th>ZONE</th><th>DERNIÈRE SOURCE</th><th>SRC.</th><th>PREUVE</th><th>IMPORTANCE</th><th>DÉCISION PROPOSÉE</th><th>RAISON PRINCIPALE</th><th>SLOT</th><th>LANGUE</th><th>POLICY</th></tr></thead><tbody>{filtered.map(event => <tr key={event.key} onClick={() => openEvent(event)}><td><code>{event.key}</code></td><td className="title">{event.title}</td><td>{event.zone}</td><td>{event.source}</td><td>{event.sources}</td><td>{event.proof}</td><td>{event.importance}</td><td><Tag tone={event.tone}>{event.decision}</Tag></td><td>{event.reason}</td><td>{event.slot}</td><td>{event.language}</td><td><code>aviationwey-v1</code></td></tr>)}</tbody></table></div><div className="table-foot">Cliquez sur une ligne pour consulter le dossier de lecture. <b>Aucune décision n’est exécutée.</b></div></div></section>

      <section className="trace card"><div className="trace-icon">?</div><div><span className="eyebrow">TRAÇABILITÉ FUTURE</span><h2>Pourquoi cette décision ?</h2><p>Une décision WeyRedaction réelle conservera <b>event_key</b>, <b>product_key</b>, <b>policy_version</b>, critères évalués, résultats des six lecteurs, décision, raison, date et opérateur ou moteur ayant proposé la décision.</p></div></section>
      </> : newsActive ? <NewsWeyPolicy /> : <section className="empty-state card"><span className="eyebrow">REGISTRE PRODUIT · AUCUNE POLITIQUE ACTIVE</span><h2>{activeProduct.name} est enregistré dans WeyRedaction</h2><p>Ce site est prêt à recevoir sa ligne éditoriale versionnée, ses critères de périmètre et son contrat de visibilité. Il n’affiche volontairement aucun candidat, aucun score ni aucune décision tant que sa policy n’est pas définie.</p><div><code>product_key: {activeProduct.key}</code><code>policy_version: à définir</code><code>publication: verrouillée</code></div></section>}
    </section>
    {panelOpen && <><div className="scrim" onClick={() => setPanelOpen(false)}/><aside className="detail" role="dialog" aria-modal="true" aria-label="Détail événement"><button className="close" onClick={() => setPanelOpen(false)} aria-label="Fermer">×</button><span className="eyebrow">DOSSIER DE LECTURE · DÉMONSTRATION</span><h2>{selected.title}</h2><code className="event-key">{selected.key}</code><div className="detail-decision"><span>Décision proposée</span><Tag tone={selected.tone}>{selected.decision}</Tag></div><p className="summary">Résumé factuel simulé : cet événement est présenté uniquement pour démontrer le parcours de lecture WeyRedaction. Aucun fait live ni statut runtime n’est affiché.</p><Detail label="Sources et diversité" value={`${selected.sources} sources signalées · diversité simulée · ${selected.source}`} /><Detail label="Entités" value="Autorité aéronautique, opérateur, appareil et zone concernés" /><Detail label="Pays / zone" value={selected.zone} /><Detail label="Statut de preuve" value={selected.proof} /><div className="detail-readers"><h3>Résultat des six lecteurs</h3>{readers.map(([num, name, , , , status, tone]) => <div key={num}><span>{num} · {name}</span><Tag tone={tone as Tone}>{status}</Tag></div>)}</div><Detail label="Raison détaillée" value={selected.reason} /><Detail label="Slot et format recommandés" value={`${selected.slot} · recommandation non exécutée`} /><Detail label="policy_version" value="aviationwey-v1" mono /><div className="not-executed">Décision non exécutée</div></aside></>}
  </main>;
}

function Detail({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="detail-field"><span>{label}</span><p className={mono ? "mono" : ""}>{value}</p></div>; }

function NewsWeyPolicyLegacy() {
  return <>
    <section className="policy card"><div className="section-title"><div><span className="eyebrow">DOSSIER ÉDITORIAL FIGÉ · VERSIONNÉ</span><h2>NewsWey V1 <Tag tone="pass">ACTIVE OBSERVATION</Tag></h2></div><Tag tone="hold">PUBLICATION LOCKED</Tag></div><div className="policy-grid"><div><b>product_key</b><code>newswey</code></div><div><b>policy_version</b><code>newswey-v1</code></div><div><b>doctrine_source</b><code>NEWSWEY_ARCHITECTURE_EDITORIALE_V3_3</code></div><div><b>mode</b><code>OBSERVATION</code></div><div className="wide"><b>Mission</b><p>Observer, hiérarchiser et expliquer les événements importants du monde à partir de faits structurés, de sources visibles et de leur contexte historique.</p></div><div><b>Promesse</b><p>Comprendre l’événement, pas le bruit.</p></div><div><b>Unité éditoriale</b><p><code>event_key</code> — un événement canonique, jamais une accumulation d’articles.</p></div><div className="wide"><b>Principes</b><p>Event-first · Importance-first · Proof-first · Context-first · sources visibles obligatoires · mémoire historique intégrée · lecture mondiale avant lecture par pays.</p></div></div></section>
    <section className="policy card news-scope"><div className="section-title"><div><span className="eyebrow">PÉRIMÈTRE NEWSWEY</span><h2>Ce que NewsWey peut traiter</h2></div></div><p>International, Politics, Security, Economy, Business, Technology & AI, Climate & Environment, Health, Science & Space, Society, Sports et Culture — seulement lorsqu’un impact réel est identifiable.</p><div className="scope-columns"><div><b>Vues de navigation, jamais générateurs d’événements</b><p>Les pays et verticales servent à naviguer. Ils ne remplissent jamais artificiellement une page et ne créent pas d’event_key.</p></div><div><b>Exclusions fixes</b><p>Rumeur insuffisante, opinion seule, promotion faible, répétition sans évolution, fragment déjà couvert, fait sans impact, titre spectaculaire sans noyau factuel ou local sans portée suffisante.</p></div></div></section>
    <section><div className="section-heading"><div><span className="eyebrow">SIX DIRECTIONS FIXES · NEWSWEY-V1</span><h2>Le comité applique le dossier, il ne l’invente pas</h2></div><span className="legend">POLICY FIGÉE · V2 requise pour toute évolution majeure</span></div><div className="reader-grid">{newsReaders.map(([num, name, question, observes, outputs, rule]) => <article className="reader card" key={num}><div className="reader-top"><span className="number">{num}</span><Tag tone="proposed">DIRECTION</Tag></div><h3>{name}</h3><strong>{question}</strong><dl><dt>Observe</dt><dd>{observes}</dd><dt>Sorties</dt><dd>{outputs}</dd><dt>Règle</dt><dd>{rule}</dd></dl></article>)}</div></section>
    <section className="intelligence card"><div><span className="eyebrow">INTELLIGENCE AUTORISÉE</span><h2>Assistants, jamais décideurs</h2><p><b>GLiNER, spaCy, KeyBERT</b> : entités, thèmes, périmètre. <b>SentenceTransformers</b> : proximité et événements liés. <b>HDBSCAN, BERTopic</b> : regroupements et tendances. <b>WeyQuery</b> : contexte historique. <b>LLM encadré</b> : explication et recommandation de format uniquement.</p></div><div className="forbidden"><b>Interdit</b><span>Créer un fait · modifier proof_status · décider seul l’importance · valider APPROVED_PUBLIC · publier</span></div></section>
    <section className="queue-section"><div className="section-heading"><div><span className="eyebrow">FILE ÉDITORIALE · SHADOW FUTUR</span><h2>File NewsWey</h2></div><Tag tone="hold">AUCUNE DONNÉE RÉELLE</Tag></div><div className="empty-state card"><p>Aucun événement réel connecté — dossier <code>newswey-v1</code> prêt pour un futur traitement shadow.</p><div><code>publication: LOCKED</code><code>APPROVED_PUBLIC: verrouillé</code><code>mode: OBSERVATION</code></div></div></section>
    <section className="trace card"><div className="trace-icon">?</div><div><span className="eyebrow">TRAÇABILITÉ NEWSWEY-V1</span><h2>Chaque future proposition est explicable</h2><p><b>event_key</b>, <b>product_key: newswey</b>, <b>policy_version: newswey-v1</b>, six résultats, critères, preuves référencées, décision proposée, raisons, format, langue, date, moteur/opérateur et statut d’exécution seront conservés.</p></div></section>
  </>;
}

function NewsWeyPolicy() {
  const tabs = ["Contenu", "Classement", "Présentation", "Cycle de vie", "Langues et sorties"] as const;
  type Tab = typeof tabs[number];
  const [tab, setTab] = useState<Tab>("Contenu");
  return <section className="news-dossier">
    <header className="news-contract card"><div className="section-title"><div><span className="eyebrow">DOSSIER ÉDITORIAL FIGÉ · CONTRAT UNIQUE</span><h2>NewsWey V1 <Tag tone="pass">ACTIVE OBSERVATION</Tag></h2></div><Tag tone="hold">PUBLICATION LOCKED</Tag></div><div className="contract-meta"><code>product_key: newswey</code><code>policy_version: newswey-v1</code><code>policy_status: ACTIVE_OBSERVATION</code><code>publication: LOCKED</code><code>unité: event_key</code></div><p>Ces cinq onglets forment un seul contrat éditorial versionné. WeyRedaction applique ce dossier ; il ne l’interprète pas librement.</p></header>
    <nav className="policy-tabs" aria-label="Dossier NewsWey">{tabs.map((name, index) => <button key={name} onClick={() => setTab(name)} className={tab === name ? "active" : ""}><span>{String(index + 1).padStart(2, "0")}</span>{name}<small>{name === "Contenu" || name === "Classement" || name === "Présentation" || name === "Cycle de vie" || name === "Langues et sorties" ? "défini" : ""}</small></button>)}</nav>
    {tab === "Contenu" && <NewsContent />}
    {tab === "Classement" && <NewsRanking />}
    {tab === "Présentation" && <NewsPresentation />}
    {tab === "Cycle de vie" && <NewsLifecycle />}
    {tab === "Langues et sorties" && <NewsLanguages />}
    <footer className="policy-final">Dossier <b>newswey-v1</b> complet — prêt pour un futur branchement WeySea en shadow lecture seule.</footer>
  </section>;
}

function NewsContent() { const families = ["International", "Politics", "Security", "Economy", "Business", "Technology & AI", "Climate & Environment", "Health", "Science & Space", "Society", "Sports", "Culture"]; return <div className="tab-panel">
  <section className="policy card"><div className="section-title"><div><span className="eyebrow">IDENTITÉ</span><h2>Comprendre l’événement, pas le bruit.</h2></div><Tag tone="proposed">NEWSWEY-V1</Tag></div><div className="policy-grid"><div className="wide"><b>Mission</b><p>Observer, hiérarchiser et expliquer les événements importants du monde à partir de faits structurés, de sources visibles et de leur contexte historique.</p></div><div><b>Promesse</b><p>Comprendre l’événement, pas le bruit.</p></div><div><b>Unité éditoriale</b><p><code>event_key</code> — un événement canonique, jamais une accumulation d’articles.</p></div><div className="wide"><b>Principes</b><p>Event-first · Importance-first · Proof-first · Context-first · sources visibles obligatoires · mémoire historique intégrée · lecture mondiale avant lecture par pays.</p></div></div></section>
  <section className="policy card news-scope"><span className="eyebrow">PÉRIMÈTRE</span><h2>Douze familles éditoriales</h2><div className="family-grid">{families.map(family => <span key={family}>{family}</span>)}</div><div className="scope-columns"><div><b>Règle de lecture</b><p>Les pays et verticales sont des vues de navigation : ils ne créent jamais artificiellement des événements ni des espaces vides.</p></div><div><b>Exclusions</b><p>Rumeur insuffisante, opinion seule, promotion faible, répétition sans évolution, fragment déjà couvert, fait sans impact, remplissage artificiel, titre spectaculaire sans noyau factuel ou actualité locale sans portée suffisante.</p></div></div></section>
  <section className="input-contract card"><span className="eyebrow">CONTRAT D’ENTRÉE FUTUR · LECTURE SEULE</span><h2>Paquet factuel attendu</h2><p>WeyRedaction recevra uniquement un paquet factuel : <code>event_key</code>, titre canonique, résumé factuel, dates, pays et zones touchés, entités, sources, proof_status, lifecycle_status, importance disponible, événements liés et dernière évolution matérielle.</p><strong>WeyRedaction ne modifie jamais ce paquet source.</strong></section>
  <section><div className="section-heading"><div><span className="eyebrow">SIX DIRECTIONS FIXES</span><h2>Le comité applique le contrat</h2></div></div><div className="reader-grid">{newsReaders.map(([num, name, question, observes, outputs, rule]) => <article className="reader card" key={num}><div className="reader-top"><span className="number">{num}</span><Tag tone="proposed">DIRECTION</Tag></div><h3>{name}</h3><strong>{question}</strong><dl><dt>Observe</dt><dd>{observes}</dd><dt>Sorties</dt><dd>{outputs}</dd><dt>Règle</dt><dd>{rule}</dd></dl></article>)}</div></section>
  <section className="intelligence card"><div><span className="eyebrow">INTELLIGENCE AUTORISÉE</span><h2>Assistants, jamais décideurs</h2><p><b>GLiNER, spaCy, KeyBERT</b> : entités, thèmes et périmètre. <b>SentenceTransformers</b> : proximité et événements liés. <b>HDBSCAN, BERTopic</b> : regroupements et tendances. <b>WeyQuery</b> : contexte historique. <b>LLM encadré</b> : explication et recommandation de format uniquement.</p></div><div className="forbidden"><b>Interdit aux moteurs et au LLM</b><span>Créer un fait · modifier proof_status · décider seul l’importance · valider APPROVED_PUBLIC · publier</span></div></section>
</div>; }

function NewsRanking() { return <div className="tab-panel"><section className="policy card"><span className="eyebrow">CLASSEMENT ÉDITORIAL NEWSWEY V1</span><h2>Importance avant récence</h2><ol className="ranking-chain">{["Vérification du périmètre", "Preuve minimale", "Importance", "Impact", "Nouveauté ou évolution matérielle", "Contexte disponible", "Fraîcheur comme critère secondaire"].map((item, i) => <li key={item}><b>{i + 1}</b>{item}</li>)}</ol><blockquote>La récence seule ne fait jamais monter un événement.</blockquote></section><section className="level-grid">{[["CRITICAL", "Conséquences humaines, sécuritaires, politiques ou économiques exceptionnelles."], ["HIGH", "Impact large, évolution significative ou portée internationale."], ["MEDIUM", "Pertinent et suffisamment prouvé, mais impact limité."], ["LOW", "Valide mais insuffisant pour une position éditoriale forte."]].map(([level, text]) => <article key={level} className="card"><Tag tone={level === "CRITICAL" ? "block" : level === "HIGH" ? "hold" : "proposed"}>{level}</Tag><p>{text}</p></article>)}</section><section className="scope-columns ranking-detail"><div className="card"><b>Éligibilité par preuve</b><p>VERIFIED : tous emplacements. DEVELOPING : badge visible et prudence. UNVERIFIED_SIGNAL : jamais APPROVED_PUBLIC. Preuve contradictoire ou insuffisante : HOLD_PROOF.</p></div><div className="card"><b>Critères explicables</b><p>Importance réelle, impact humain, portée, secteurs affectés, nouveauté, évolution matérielle, continuité, contexte et diversité des preuves.</p></div></section><section className="contract-demo card"><span className="eyebrow">CONTRAT DE DÉMONSTRATION · AUCUNE DONNÉE RÉELLE</span><h2>Sortie de classement future</h2><div>{["event_key", "rank_level", "proof_status", "reason_codes", "previous_rank", "recommended_rank", "policy_version"].map(key => <code key={key}>{key}</code>)}</div><p>Le score ne remplace jamais les raisons. Chaque classement conserve ses <code>reason_codes</code> ; une évolution matérielle peut faire remonter un événement ancien encore important.</p></section></div>; }

function NewsPresentation() { const slots = ["Breaking Bar", "Lead Event", "Major Grid", "Vertical Lanes", "Continuous Feed", "Dossier", "Timeline", "Video Wall"]; return <div className="tab-panel"><section className="policy card"><span className="eyebrow">CONTRAT DE PRÉSENTATION NEWSWEY V1</span><h2>Recommandation, exécution, affichage</h2><blockquote>WeyRedaction recommande la composition. WeyOutput l’exécute. NewsWey.com l’affiche sans redécider.</blockquote><p>Un <code>event_key</code> possède un emplacement principal ; il peut être référencé par pays ou verticale sans devenir un nouvel événement. Aucun emplacement n’est rempli artificiellement : sans contenu valable, la section est masquée.</p></section><section className="composition-preview card"><span className="eyebrow">PRÉVISUALISATION LOCALE · BLOCS VIDES</span><div className="slot-grid">{slots.map(slot => <div key={slot}>{slot}<small>aucun événement connecté</small></div>)}</div></section><section className="scope-columns"><div className="card"><b>Carte NewsWey</b><p>Titre canonique factuel, résumé court, importance, verticale, pays/zone, source principale et nombre de sources, proof_status, dernière évolution, média qualifié et lien vers page canonique.</p></div><div className="card"><b>Détail de l’événement</b><p>NOW · WHY NOW · WHY IT MATTERS · LAST TIME si disponible · TREND si prouvé · SOURCES. Le proof_status reste toujours visible.</p></div></section><div className="manifest-flow"><code>WeyRedaction</code><span>→</span><code>publication_manifest</code><span>→</span><code>WeyOutput</code><span>→</span><code>NewsWey.com</code></div></div>; }

function NewsLifecycle() { const rules = [["Breaking Bar", "réévaluation rapide ; rétrogradation après 2 h sans évolution matérielle"], ["Lead Event", "réévaluation après 6 h"], ["Major Grid", "réévaluation après 12 h"], ["Vertical Lane", "réévaluation après 24 h"], ["Continuous Feed", "visibilité active jusqu’à 48 h selon importance"], ["Dossier / Timeline", "conservation durable"], ["Page canonique", "conservation permanente"]]; return <div className="tab-panel"><section className="policy card"><span className="eyebrow">VISIBILITÉ ET RÉÉVALUATION</span><h2>Le temps ne supprime pas la mémoire</h2><blockquote>Le temps déclenche une réévaluation. Il ne supprime jamais automatiquement la mémoire de l’événement.</blockquote></section><section className="lifecycle-grid">{rules.map(([slot, rule]) => <article className="card" key={slot}><b>{slot}</b><p>{rule}</p></article>)}</section><section className="scope-columns"><div className="card"><b>Comportements</b><p>Nouveau fait : enrichir le même event_key et reclasser. Sans évolution : réduire progressivement la visibilité. Événement terminé : retirer des positions actives, conserver la page. Durable : Timeline ou Dossier.</p></div><div className="card"><b>Contradiction et relance</b><p>Contradiction majeure : HOLD_PROOF ou REVIEW_REQUIRED. Relance réelle : réévaluer sans créer automatiquement un doublon.</p></div></section><section className="state-list card"><span className="eyebrow">ÉTATS DU GATE</span><div>{["PROPOSED", "HOLD_SCOPE", "HOLD_PROOF", "HOLD_IMPORTANCE", "HOLD_CONTEXT", "REVIEW_REQUIRED", "APPROVED_PUBLIC", "BLOCKED", "ARCHIVED"].map(state => <code key={state}>{state}</code>)}</div><p>APPROVED_PUBLIC reste verrouillé en mode observation.</p></section></div>; }

function NewsLanguages() { const manifests = ["web_manifest", "pwa_manifest", "notification_manifest", "social_manifest", "short_video_manifest", "newsletter_manifest"]; return <div className="tab-panel"><section className="policy card"><span className="eyebrow">LANGUES, CANAUX ET RÉUTILISATION</span><h2>English par défaut, vérité unique</h2><div className="scope-columns"><div><b>Règles de langue</b><p>Conserver la langue source. Choisir d’abord la valeur éditoriale. Produire l’anglais par défaut, les autres langues à la demande ; traduire après validation, mettre en cache, ne jamais retraduire l’inchangé.</p></div><div><b>Clé future de traduction</b><p><code>event_key + content_revision + language + policy_version</code></p><p>En cas d’évolution, conserver le même event_key, créer une nouvelle content_revision et retraduire seulement les champs modifiés.</p></div></div></section><section className="policy card"><span className="eyebrow">SORTIES PRÉVUES</span><h2>Une décision, plusieurs présentations</h2><p>Site web · PWA · Notification · Réseaux sociaux · Vidéo courte · Newsletter</p><blockquote>Une seule décision éditoriale peut produire plusieurs manifestes de présentation. Chaque canal adapte le format, jamais la vérité du contenu.</blockquote><div className="manifest-list">{manifests.map(manifest => <code key={manifest}>{manifest}</code>)}</div><p className="muted">Aucun manifeste n’est envoyé dans cette V1.</p></section></div>; }
